// Generated by https://quicktype.io

export interface Users {
  data:  Datum[];
  links: Links;
  meta:  Meta;
}

export interface Datum {
  id:                 number;
  name:               string;
  email:              string;
  volunteeringFields: VolunteeringFields | null;
}

export interface VolunteeringFields {
  user_id:        number;
  marital_status: string;
  id_type:        string;
  id_number:      string;
  phone_number:   string;
  mobile_number:  string;
  linkedin_url:   string;
  gender:         string;
  birthday:       null;
}

export interface Links {
  first: string;
  last:  string;
  prev:  null;
  next:  string;
}

export interface Meta {
  current_page: number;
  from:         number;
  last_page:    number;
  path:         string;
  per_page:     number;
  to:           number;
  total:        number;
}
